// Website configuration - Auto-generated by Terminal Website Generator
const WEBSITE_CONFIG = {
    siteName: 'omnet.dev',
    firstName: 'Omar',
    lastName: 'Mustafa',
    fullName: 'Omar Mustafa',
    email: 'omar@omnet.dev',
    linkedinUrl: '',
    githubUrl: 'https://github.com/odmustafa',
    skills: '[H[2J[3J[H[2J[3J[0;36m╔══════════════════════════════════════════════════════════════╗[0m
[0;36m║[0m  [0;32m🖥️  Terminal Website Generator - Interactive Setup[0m      [0;36m║[0m
[0;36m╚══════════════════════════════════════════════════════════════╝[0m

[1;33mSelect Your Skills:[0m
[0;34mUse ↑↓ to navigate, SPACE to select/deselect, ENTER to confirm[0m

  [0;36m► [ ] HTML5 & CSS3[0m
    [ ] JavaScript (ES6+)
    [ ] React.js
    [ ] Vue.js
    [ ] Angular
    [ ] Node.js
    [ ] Express.js
    [ ] Python
    [ ] PHP
    [ ] Laravel
    [ ] WordPress
    [ ] MySQL
    [ ] MongoDB
    [ ] PostgreSQL
    [ ] Git & Version Control
    [ ] Responsive Web Design
    [ ] UI/UX Design
    [ ] Adobe Creative Suite
    [ ] Figma
    [ ] Sketch
    [ ] Bootstrap
    [ ] Tailwind CSS
    [ ] SASS/SCSS
    [ ] TypeScript
    [ ] jQuery
    [ ] REST APIs
    [ ] GraphQL
    [ ] Docker
    [ ] AWS
    [ ] Google Cloud
    [ ] SEO Optimization
    [ ] Google Analytics
    [ ] Social Media Marketing
    [ ] Content Marketing
    [ ] Email Marketing
    [ ] PPC Advertising
    [ ] Brand Strategy
    [ ] Graphic Design
    [ ] Logo Design
    [ ] Print Design
    [ ] Web Hosting
    [ ] Domain Management

[0;35mSelected: 0 items[0m',
    certifications: '[H[2J[3J[H[2J[3J[0;36m╔══════════════════════════════════════════════════════════════╗[0m
[0;36m║[0m  [0;32m🖥️  Terminal Website Generator - Interactive Setup[0m      [0;36m║[0m
[0;36m╚══════════════════════════════════════════════════════════════╝[0m

[1;33mSelect Your Certifications:[0m
[0;34mUse ↑↓ to navigate, SPACE to select/deselect, ENTER to confirm[0m

  [0;36m► [ ] Google Analytics Certified[0m
    [ ] Google Ads Certified
    [ ] Google Cloud Professional
    [ ] AWS Certified Developer
    [ ] AWS Certified Solutions Architect
    [ ] Microsoft Azure Certified
    [ ] Adobe Certified Expert (ACE)
    [ ] Facebook Blueprint Certified
    [ ] HubSpot Certified
    [ ] Salesforce Certified
    [ ] CompTIA A+
    [ ] CompTIA Security+
    [ ] Cisco CCNA
    [ ] Project Management Professional (PMP)
    [ ] Scrum Master Certified
    [ ] Google UX Design Certificate
    [ ] Meta Front-End Developer
    [ ] Meta Back-End Developer
    [ ] freeCodeCamp Certifications
    [ ] Coursera Specializations
    [ ] Udemy Certifications
    [ ] LinkedIn Learning Certificates
    [ ] Oracle Certified Professional
    [ ] Red Hat Certified Engineer
    [ ] Shopify Partner Certification
    [ ] WooCommerce Expert
    [ ] Magento Certified Developer
    [ ] Drupal Certified
    [ ] Webflow Expert
    [ ] Squarespace Specialist

[0;35mSelected: 0 items[0m',
    services: '[H[2J[3J[H[2J[3J[0;36m╔══════════════════════════════════════════════════════════════╗[0m
[0;36m║[0m  [0;32m🖥️  Terminal Website Generator - Interactive Setup[0m      [0;36m║[0m
[0;36m╚══════════════════════════════════════════════════════════════╝[0m

[1;33mSelect Services You Offer:[0m
[0;34mUse ↑↓ to navigate, SPACE to select/deselect, ENTER to confirm[0m

  [0;36m► [ ] Website Development[0m
    [ ] E-commerce Development
    [ ] Mobile App Development
    [ ] Custom Web Applications
    [ ] WordPress Development
    [ ] Shopify Store Setup
    [ ] Website Redesign
    [ ] Landing Page Creation
    [ ] UI/UX Design
    [ ] Graphic Design
    [ ] Logo Design
    [ ] Brand Identity Design
    [ ] Print Design
    [ ] Social Media Graphics
    [ ] SEO Optimization
    [ ] Google Ads Management
    [ ] Social Media Marketing
    [ ] Content Marketing
    [ ] Email Marketing
    [ ] Marketing Automation
    [ ] Website Maintenance
    [ ] Website Hosting
    [ ] Domain Registration
    [ ] SSL Certificate Setup
    [ ] Website Security
    [ ] Performance Optimization
    [ ] Database Development
    [ ] API Development
    [ ] Third-party Integrations
    [ ] Payment Gateway Setup
    [ ] Analytics Setup
    [ ] Consulting Services
    [ ] Training & Workshops
    [ ] Technical Support
    [ ] Project Management

[0;35mSelected: 0 items[0m',
    adminPass: 'Genpack4007!'
};
